### ISSUE TITLE
i died

### ISSUE THREAD

**Issue by ThatOneCalculator** [floppydiskette/cursh#1]
i used this and fukin collapesed on the floor,,, what is buisnes address so i can suee!! :trollface:

**Comment by floppydiskette** [comment]
email billgate@realmicrosoft.com for any problems you have with cursh!
we are not responsible for injuries or deaths!! (smh you'd know this if u read the license)

**Comment by ThatOneCalculator** [comment]
MIT stands for Mmmmm I Tried

**Comment by floppydiskette** [comment]
mit stands for deez what's deez deez limga balls 😂
